
version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: docker/web.docker
        container_name: auther-nginx
        volumes:
            - ./:/var/www
        ports:
            - "8090:80"
        links:
            - app
        logging:
          options:
            max-size: 50m
        networks:
          vpcbr:
            ipv4_address: 172.20.0.2
    app:
        build:
            context: ./
            dockerfile: docker/app.docker
        container_name: auther-php
        volumes:
            - ./:/var/www
        environment:
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
        logging:
          options:
            max-size: 50m
        networks:
          vpcbr:
            ipv4_address: 172.20.0.3
    database:
        image: mysql:5.6
        container_name: auther-mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=defaultPassword"
            - "MYSQL_DATABASE=auther"
        ports:
            - "33062:3306"
        networks:
          vpcbr:
            ipv4_address: 172.20.0.4
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
